# Generated by Django 4.2.16 on 2025-06-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('exchange', models.CharField(max_length=10)),
                ('validity', models.CharField(choices=[('DAY', 'Day'), ('IOC', 'IOC')], max_length=10)),
                ('order_type', models.CharField(choices=[('LIMIT', 'Limit'), ('MARKET', 'Market'), ('SL', 'Stop Loss')], max_length=10)),
                ('order_mode', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.CharField(choices=[('INTRADAY', 'Intraday'), ('DELIVERY', 'Delivery'), ('MARGIN', 'Margin')], max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('fyers_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
