# Generated by Django 4.2.16 on 2025-06-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_tradeorder_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeorder',
            name='timestamp',
        ),
    ]
