# Generated by Django 4.2.16 on 2025-07-10 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_tradeorder_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorder',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='parent_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='revisit_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
